#!/bin/bash


curl -H "Authorization: Basic Base64Encoded String Here 'User:Password'" https://dynupdate.no-ip.com/nic/update?hostname=bullfreak.zapto.org&myip=`curl https://api.ipify.org`
curl -H "Authorization: Basic Base64Encoded String Here 'User:Password'" https://dynupdate.no-ip.com/nic/update?hostname=bullfreak.zapto.org&myip=`curl ifconfig.me`

#curl https://user:password@dynupdate.no-ip.com/nic/update?hostname=bullfreak.zapto.org&myip=`curl ifconfig.me`
