#!/bin/bash
set -ue

myip=`curl https://api.ipify.org`
echo $myip
echo "curl -X POST -d 'Authorization: Basic NEdrUkhPQzNkM05JNUVQMDo0SnpaWFZVN1NobjMwMW5vCg==' https://domains.google.com/nic/update?hostname=bullsilver.farsos.ca&myip=$myip"
