#!/bin/bash
echo $#
while [ $# -ge 1 ]; do
	if [[ $1 =~ ^- ]]; then
		shift
		continue
	fi
	echo 'line 7'
	murder=$1
	if [[ $murder =~ ^\/$ ]]; then
	echo -e "
		I don't know who you are, but you tried to kill my baby
		\nI advise you leave now because if you continue down this path
 		\nI promise you this your actions will come back to haunt you
 	 	\nand when they do, no one will be able to help you
 		"
    	return 1
  	fi
	echo "line 18 murder=$murder"
  	#get the full path of the file or folder I want dead
  	oPath=$(readlink -f $murder)
	echo "line 21 oPath=$oPath"
  	#drop the / if it's a directoryg
  	if [[ $murder =~ (.*)\/$ ]];then
		murder=${BASH_REMATCH[1]}
		oPath="$oPath/"
  	fi
	echo "line 27 oPath=$oPath"
  	#move the file to the ubuntu trash bin (could be natulus the file manager)
  	mv $oPath ~/.local/share/Trash/files/
  	#create an entry in said trashbin
  	echo -e "[Trash Info]\nPath=$oPath\nDeletionDate=$(date +%d-%m-%YT%H:%M:%S)" >> ~/.local/share/Trash/info/$murder.trashinfo
	shift
done
