#!/bin/bash

curl https://kingsukhoi:cell00highway@dynupdate.no-ip.com/nic/update?hostname=bullfreak.zapto.org&myip=`curl ifconfig.me`
#wget https://a2luZ3N1a2hvaTpjZWxsMDBoaWdod2F5@dynupdate.no-ip.com/nic/update?hostname=bullfreak.zapto.org&myip=`curl ifconfig.me`
