#!/bin/bash
set -ue
name="`pwd`/$1"


if [[ -f $name ]]; then

	echo "file exists" >&2 
	exit 1
fi

touch $name
chmod u+x $name

while :; do
    case $1 in
        -p | --python)
            echo "#!/usr/bin/env python3"
            break
            ;;
        *)
            echo -e "#!/bin/bash \n set -ue" >> $name
            break
            ;;
    esac
    shift
done

vim $name

