#!/bin/bash
set -ue
while [ $# -ge 1 ]; do
	if [[ "$1" =~ ^- ]]; then
		shift
		continue
	fi
	murder="$1"
	if [[ $murder =~ '^/$' ]]; then
	echo "
I don't know who you are, but you tried to kill my baby
I advise you leave now because if you continue down this path
Your actions will come back to haunt you
and when they do, no one will be able to help you
	"
    	exit 1
  	fi
	#check if file exists
	#if [ ! -e "$murder" ]; then 
	if ! find "$murder" &> /dev/null ; then
        echo "$murder no exist"
		shift
		continue
	fi
	#if the file is a link use the actual rm program to kill it
	if [[ -L "$murder" ]]; then
		/bin/rm "$murder"
		shift
		continue	
	fi
  	#get the full path of the file or folder I want dead
 	oPath=$(readlink -f "$murder")
  	#drop the / if it's a directory
  	regex="(.*)\\/$"
	if [[ $murder =~ $regex  ]];then
		murder=${BASH_REMATCH[1]}
		oPath="$oPath"
 	fi
 	#move the file to the ubuntu trash bin (could be natulus the file manager)
	#check if file of the same name exists
	dest="$HOME/.local/share/Trash/files/"	
	
	if [[ -e "$dest$murder" ]]; then
		/bin/rm -rf "$dest$murder"
	fi
	mv "$oPath" "$dest" 
	
 	#create an entry in said trashbin
	tinfoFile="$HOME/.local/share/Trash/info/$murder.trashinfo"
	touch "$tinfoFile"

  	echo -e -n "[Trash Info]\\nPath=$oPath\\nDeletionDate=$(date +%d-%m-%YT%H:%M:%S)" > "$tinfoFile" 
	shift
done
